[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_DEFAULT_DEPT_CODE = "0000"

[functions]
  timeout = 26

[[plugins]]
  package = "@netlify/plugin-nextjs"
